### ISSUE TITLE
Different hash from expected at end of docker build?

### ISSUE THREAD

**Issue by vincentadultman** [talex5/qubes-mirage-firewall#21]
Build environment: FC26 appvm on Qubes 3.2

Following the instructions given in the "build" section of Readme.md Another recent user suggests to me the hashes should match at the end of the proces

SHA2 of build:   402ede3231a4e41a3709c5c3a2f5afa1bc7b5345bee40e4de077a13f22861f86  qubes_firewall.xen
SHA2 last known: 2cad66c4b83817cdd1650f174586fd4daab7b7c271abd62844de6e6a17200750

Let me know if I can be of any assistance (re-running same n times, copy of full build output etc).

**Comment by talex5** [comment]
The git version is pinning the latest version of mirage-net-xen (because the released version is missing a feature we need). But that means that the hash might change, so I didn't update it. Once the new version of mirage-net-xen is out, I'll remove the pin and update the hash.

The SHA2 hash should match for released versions of mirage-firewall though.

(I also get `402ede3231a4e41a3709c5c3a2f5afa1bc7b5345bee40e4de077a13f22861f86` currently)

**Comment by yomimono** [comment]
`netchannel` and `mirage-net-xen` both, or just `mirage-net-xen`?

**Comment by talex5** [comment]
Sorry, I was being vague there:

We need a new release of the `netchannel` opam package from the `mirage-net-xen` repository.

(this name change is a bit confusing!)

**Comment by yomimono** [comment]
OK.  Once someone merges https://github.com/mirage/mirage-net-xen/pull/71I'll take care of the rest.

**Comment by talex5** [comment]
Done :-) Thanks for taking care of this - I've been meaning to do it myself for a while now...

**Comment by yomimono** [comment]
No problem; I've also been meaning to do it myself for a while now.  [opam-repository PR is here](https://github.com/ocaml/opam-repository/pull/11033).
